embeddings {
  tensor_name: "User Embeddings:00000"
  metadata_path: "00000/User Embeddings/metadata.tsv"
  tensor_path: "00000/User Embeddings/tensors.tsv"
}
embeddings {
  tensor_name: "Item Embeddings:00000"
  metadata_path: "00000/Item Embeddings/metadata.tsv"
  tensor_path: "00000/Item Embeddings/tensors.tsv"
}
embeddings {
  tensor_name: "User Embeddings:00000"
  metadata_path: "00000/User Embeddings/metadata.tsv"
  tensor_path: "00000/User Embeddings/tensors.tsv"
}
embeddings {
  tensor_name: "Item Embeddings:00000"
  metadata_path: "00000/Item Embeddings/metadata.tsv"
  tensor_path: "00000/Item Embeddings/tensors.tsv"
}
embeddings {
  tensor_name: "User Embeddings:00000"
  metadata_path: "00000/User Embeddings/metadata.tsv"
  tensor_path: "00000/User Embeddings/tensors.tsv"
}
embeddings {
  tensor_name: "Item Embeddings:00000"
  metadata_path: "00000/Item Embeddings/metadata.tsv"
  tensor_path: "00000/Item Embeddings/tensors.tsv"
}
embeddings {
  tensor_name: "User Embeddings:00000"
  metadata_path: "00000/User Embeddings/metadata.tsv"
  tensor_path: "00000/User Embeddings/tensors.tsv"
}
embeddings {
  tensor_name: "Item Embeddings:00000"
  metadata_path: "00000/Item Embeddings/metadata.tsv"
  tensor_path: "00000/Item Embeddings/tensors.tsv"
}
embeddings {
  tensor_name: "User Embeddings - nn.Embedding:00000"
  metadata_path: "00000/User Embeddings - nn.Embedding/metadata.tsv"
  tensor_path: "00000/User Embeddings - nn.Embedding/tensors.tsv"
}
embeddings {
  tensor_name: "Item Embeddings - nn.Embedding:00000"
  metadata_path: "00000/Item Embeddings - nn.Embedding/metadata.tsv"
  tensor_path: "00000/Item Embeddings - nn.Embedding/tensors.tsv"
}
embeddings {
  tensor_name: "User Embeddings - IMPROVED:00000"
  metadata_path: "00000/User Embeddings - IMPROVED/metadata.tsv"
  tensor_path: "00000/User Embeddings - IMPROVED/tensors.tsv"
}
embeddings {
  tensor_name: "Item Embeddings - IMPROVED:00000"
  metadata_path: "00000/Item Embeddings - IMPROVED/metadata.tsv"
  tensor_path: "00000/Item Embeddings - IMPROVED/tensors.tsv"
}
embeddings {
  tensor_name: "User Embeddings - IMPROVED_country:00000"
  metadata_path: "00000/User Embeddings - IMPROVED_country/metadata.tsv"
  tensor_path: "00000/User Embeddings - IMPROVED_country/tensors.tsv"
}
embeddings {
  tensor_name: "User Embeddings - IMPROVED_country:00000"
  metadata_path: "00000/User Embeddings - IMPROVED_country/metadata.tsv"
  tensor_path: "00000/User Embeddings - IMPROVED_country/tensors.tsv"
}
embeddings {
  tensor_name: "Item Embeddings - IMPROVED_country:00000"
  metadata_path: "00000/Item Embeddings - IMPROVED_country/metadata.tsv"
  tensor_path: "00000/Item Embeddings - IMPROVED_country/tensors.tsv"
}
